version: '3.8'

services:
  1.models.minio:
    image: minio/minio:RELEASE.2023-06-29T05-12-28Z
    container_name: 1.models.minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio-1:/data,size=10G
    command: server --console-address ":9001" /data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 256m
          cpus: '0.25'
    networks:
      - game-shop-network

networks:
  game-shop-network:
    driver: bridge